name: Ninja build

on:
  workflow_dispatch:

jobs:
  interactive-shell:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. SSH Authorized Key Setup
      - name: Setup SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PUBLIC_KEY }}
          known_hosts: unneeded

      # 2. Start Pinggy TCP Tunnel (Free, No Card, Direct TCP)
      - name: Start SSH Tunnel
        run: |
          ssh -o StrictHostKeyChecking=no -p 443 -R0:localhost:22 a.pinggy.io > pinggy.log 2>&1 &
          sleep 5
          
          echo "======================================================="
          echo "DIRECT SSH CONNECTION COMMAND:"
          grep -o 'ssh -p [0-9]* .*@a.pinggy.io' pinggy.log || cat pinggy.log
          echo "======================================================="

          # Session ko active rakhne ke liye
          tail -f /dev/null
