name: Terminal

on:
  workflow_dispatch:

jobs:
  interactive-shell:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Ngrok SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PUBLIC_KEY }}
          known_hosts: unneeded

      - name: Start Ngrok Tunnel
        env:
          NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
        run: |
          curl -s https://bin.equinox.io/c/bNyA1xQZYv/ngrok-v3-stable-linux-arm64.tgz | tar xz
          ./ngrok config add-authtoken $NGROK_AUTHTOKEN
          ./ngrok tcp 22 --log=stdout &
          sleep 5
          curl -s http://localhost:4040/api/tunnels | grep -o 'tcp://[^"]*'
          tail -f /dev/null
